# CircleCI 2.0 configuration file. See <https://circleci.com/docs/2.0/language-python/>.
version: 2
jobs:
  build:
    docker:
      - image: python:3.8

    steps:
      - checkout

      - restore_cache:
          key: v1-py3-deps-{{ .Branch }}-{{ checksum "setup.py" }}

      - run:
          name: Create a virtualenv
          command: |
            mkdir -p /tmp/venv/openfisca_france_fiscalite_miniere
            python -m venv /tmp/venv/openfisca_france_fiscalite_miniere
            echo "source /tmp/venv/openfisca_france_fiscalite_miniere/bin/activate" >> $BASH_ENV

      - run:
          name: Install dependencies
          command: |
            make build

      - save_cache:
          key: v1-py3-deps-{{ .Branch }}-{{ checksum "setup.py" }}
          paths:
            - /tmp/venv/openfisca_france_fiscalite_miniere

      - save_cache:
          key: v1-py3-build-{{ .Revision }}
          paths:
            - dist

      - run:
          name: Run tests
          command: make test

  check_version_and_changelog:
    docker:
      - image: python:3.8

    steps:
      - checkout

      - run:
          name: Check version number has been properly updated
          command: |
            git fetch
            .circleci/is-version-number-acceptable.sh

  deploy:
    docker:
      - image: python:3.8
    environment:
      PYPI_USERNAME: openfisca-bot  # Edit this value to replace it by your Pypi username
      # PYPI_PASSWORD: this value is set in CircleCI's web interface; do not set it here, it is a secret!

    steps:
      - checkout

      - restore_cache:
          key: v1-py3-deps-{{ .Branch }}-{{ checksum "setup.py" }}

      - restore_cache:
          key: v1-py3-build-{{ .Revision }}

      - run:
          name: Check for functional changes
          command: if ! .circleci/has-functional-changes.sh ; then circleci step halt ; fi

      - run:
          name: Upload a Python package to Pypi
          command: |
            source /tmp/venv/openfisca_france_fiscalite_miniere/bin/activate
            twine upload dist/* --username $PYPI_USERNAME --password $PYPI_PASSWORD

      - run:
          name: Publish a git tag
          command: .circleci/publish-git-tag.sh

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - check_version_and_changelog
      - deploy:
          requires:
            - build
            - check_version_and_changelog
          filters:
            branches:
              only: master
